# Generated by Django 5.2.16 on 2026-07-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(help_text="Utilisé dans l'URL, ex: agriscore", unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('mobile', 'Mobile'), ('web', 'Web'), ('erp', 'ERP')], max_length=20, verbose_name='Catégorie')),
                ('short_description', models.CharField(max_length=200, verbose_name='Description courte')),
                ('description', models.TextField(verbose_name='Description complète')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Image (carte)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Image (détail)')),
                ('tech_stack', models.CharField(help_text='Ex: Flutter, Dart, Provider', max_length=200, verbose_name='Technologies')),
                ('github_url', models.URLField(blank=True, verbose_name='Lien GitHub')),
                ('demo_url', models.URLField(blank=True, verbose_name='Lien démo')),
                ('client', models.CharField(blank=True, help_text='Ex: Projet académique L2', max_length=100, verbose_name='Client / Contexte')),
                ('project_date', models.DateField(blank=True, null=True, verbose_name='Date du projet')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('featured', models.BooleanField(default=True, verbose_name='Mettre en avant')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['order', '-project_date'],
            },
        ),
    ]
