# Generated by Django 5.2.16 on 2026-07-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('web', 'Web'), ('erp', 'ERP'), ('desktop', 'Desktop')], max_length=20, verbose_name='Catégorie'),
        ),
    ]
